apiVersion: v1
kind: Service
metadata:
    name: "k8s4php-da6e"
    labels:
        app: "k8s4php-da6e"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "k8s4php-da6e"